# 主配置文件 - 包含所有环境的通用配置
spring:
  profiles:
    active: @profiles.active@  # 使用 Maven 的 profile 占位符，默认值在 pom.xml 中定义
  
  # 应用基本信息
  application:
    name: survey-master
  
  # Jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# MyBatis 配置 - 所有环境通用
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.practice.surveymaster.model
  type-handlers-package: org.practice.surveymaster.config
  configuration:
    map-underscore-to-camel-case: true

# 数据脱敏配置
sensitive:
  enabled: true              # 是否启用数据脱敏功能
  enable-log: true           # 是否在日志中启用脱敏
  enable-json: true          # 是否在 JSON 序列化时启用脱敏
  default-mask-char: "*"     # 默认的脱敏字符

# JWT配置
jwt:
  secret: surveymaster-jwt-secret-key-for-authentication-very-secure-2025
  access-token-expiration: 7200000      # 访问令牌过期时间（毫秒）- 2小时
  refresh-token-expiration: 604800000   # 刷新令牌过期时间（毫秒）- 7天
  token-header: Authorization           # token请求头名称
  token-prefix: "Bearer "               # token前缀

# 默认日志配置 - 可被各环境覆盖
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"


